/CRY/input returnMuons 1
/CRY/input returnNeutrons 0
/CRY/input returnProtons 0
/CRY/input returnGammas 0
/CRY/input returnPions 0
/CRY/input returnKaons 0
/CRY/input date 9-02-2016
/CRY/input latitude 33.6
/CRY/input altitude 0
/CRY/input subboxLength 1
/CRY/update  

# Initialize kernel
/run/initialize
/event/verbose 0
/run/verbose 0
/run/beamOn 1000
# comment out "exit" in the next line, to keep the display window.
# exit

